apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-challenge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-challenge
  template:
    metadata:
      labels:
        app: devops-challenge
    spec:
      containers:
      - name: devops-challenge
        image: devops-challenge
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9900
